"""New version

Revision ID: 968c51b93681
Revises: 
Create Date: 2025-05-27 12:41:50.435428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '968c51b93681'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_logins_id'))
        batch_op.drop_index(batch_op.f('ix_logins_username'))

    op.drop_table('logins')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logins',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=True),
    sa.Column('password', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('logins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_logins_username'), ['username'], unique=1)
        batch_op.create_index(batch_op.f('ix_logins_id'), ['id'], unique=False)

    # ### end Alembic commands ###
